FROM node:lts-alpine

RUN npm install -g http-server

WORKDIR /home/app

COPY ./web/package.json /home/app
COPY ./web/package-lock.json /home/app

RUN npm install -g npm@9.2.0

COPY ./web /home/app


# https://stackoverflow.com/questions/75570207/nodeinternal-modules-cjs-loader1078-throw-err
# https://github.com/karthikeyanrathore/MedSonic/actions/runs/4532505545/jobs/7983981965#step:3:230
RUN npm i -g stylelint@version

RUN npm run build

EXPOSE 8080
CMD [ "http-server", "dist" ]
