FROM node:lts-alpine

RUN npm install -g http-server

WORKDIR /home/app

COPY ./web/package.json /home/app
COPY ./web/package-lock.json /home/app

RUN npm install -g npm@9.2.0

COPY ./web /home/app

# https://github.com/addyosmani/a11y/issues/13#issuecomment-67204681
RUN npm install chalk

RUN npm run build

EXPOSE 8080
CMD [ "http-server", "dist" ]
